### ISSUE TITLE
PiCANet experiment in the paper

### ISSUE THREAD

**Issue by ahyunSeo** [jiwei0921/DMRA_RGBD-SOD#3]
Hello,

Thank you for your nice work.
I have some questions with the Table 1 in your paper.
Did you train/test RGB methods with the RGB images in the RGBD datasets from scratch? or finetune their pretrained model?
For PiCANet, which backbone did you use for your table? Is it VGG16 or ResNet?

Thank you.
Best regards,
Ahyun

**Comment by jiwei0921** [comment]
Hi，thank you for your interests. It's my pleasure
For test RGB methods, we directly use their pretrained model or provided results from author due to the smaller RGBD training dataset than RGB.
For PiCANet, we use pretrained model based on Resnet for prediction with best results

**Comment by ahyunSeo** [comment]
Thanks alot!
